### ISSUE TITLE
unable to install "amplicon"

### ISSUE THREAD

**Issue by AliceDXYu** [YongxinLiu/MicrobiomeStatPlot#1]
Hi Yongxin,
Thank you for developing the package "amplicon". When I tried to install it, I got the following error and warnings. Do you have any suggestions on how to solve them? Thanks.

Error: Failed to install 'amplicon' from GitHub:
  (converted from warning) unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.6:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.6/PACKAGES'
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by YongxinLiu** [comment]
目前3.6版本已经不再维护，建议使用4.0安装。

4.0安装如果有问题，可以下载全部的R包和依赖关系，详见 https://github.com/YongxinLiu/MicrobiomeStatPlot/blob/master/Data/BigDataDownlaodList.md ，然下解压替换即可
